M48
; DRILL file {KiCad 7.0.2-6a45011f42~172~ubuntu22.04.1} date Wed 03 May 2023 10:24:55 AM PDT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-03T10:24:55-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-6a45011f42~172~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0335
%
G90
G05
T1
X4.1641Y-5.2026
X4.2822Y-5.2026
T0
M30
