M48
; DRILL file {KiCad 7.0.5} date Fri 23 Jun 2023 03:18:34 PM PKT
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-06-23T15:18:34+05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0472
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0906
%
G90
G05
T1
X5.5226Y-4.7047
T2
X5.5207Y-3.878
T3
X5.9075Y-3.8366
X5.9075Y-4.6673
T0
M30
