M48
; DRILL file {KiCad 6.0.10-86aedd382b~118~ubuntu20.04.1} date Wed 01 Feb 2023 03:49:50 PM PST
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-02-01T15:49:50-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.10-86aedd382b~118~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0335
%
G90
G05
T1
X3.2497Y-6.2506
X3.2497Y-6.4781
T2
X3.2709Y-5.9061
X3.3891Y-5.9061
T0
M30
